version: '3.9'

networks:
  misw4410-network:
    driver: bridge

services:
  db:
    image: postgres:14-alpine
    container_name: misw4410-db
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - misw4410-network

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: misw4410-app
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    networks:
      - misw4410-network
    command: ["dockerize", "-wait", "tcp://db:5432", "-timeout", "30s", "python", "app.py"]